# Generated by Django 6.0.6 on 2026-06-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Add',
        ),
    ]
